import type { UpdateState } from "../shared/workspace";
import type { OutlineItem } from "@/types/navigation";

export type MarkdownEditorProps = {
  content: string;
  fileName: string | null;
  filePath: string | null;
  workspaceRootPath?: string | null;
  saveStateLabel: string;
  wordCount: number;
  readingTime: number;
  onChange: (value: string) => void;
  onToggleSidebar?: () => void;
  isSidebarCollapsed?: boolean;
  onCreateNote?: () => void;
  toggleSidebarShortcut?: string;
  newNoteShortcut?: string;
  onOpenSettings?: () => void;
  onOpenCommandPalette?: () => void;
  onOpenLinkedFile?: (path: string) => void;
  commandPaletteShortcut?: string;
  onNavigateBack?: () => void;
  onNavigateForward?: () => void;
  navigateBackShortcut?: string;
  navigateForwardShortcut?: string;
  canGoBack?: boolean;
  canGoForward?: boolean;
  autoOpenPDFSetting?: boolean;
  isActiveFileFavorite?: boolean;
  isActiveFilePinned?: boolean;
  onOutlineJumpHandled?: () => void;
  onToggleFavoriteFile?: () => void;
  updateState?: UpdateState | null;
  onUpdateAction?: () => void;
  isFocusMode?: boolean;
  showOutline?: boolean;
  onToggleFocusMode?: () => void;
  focusModeShortcut?: string;
  onOpenNewWindow?: () => void;
  onDeleteNote?: () => void;
  onTogglePinnedFile?: () => void;
  folderRevealLabel?: string;
  outlineItems?: OutlineItem[];
  outlineJumpRequest?: { id: string; nonce: number } | null;
};

export type MarkdownEditorToast = {
  title: string;
  description: string;
};
